Enable Multi-Arch Builds and Verification via CircleCI
NVIDIA/open-gpu-kernel-modules pull request #111
Opened 2022-05-12 17:07 UTC by james-crowley

Added CircleCI to handle CI/CD needs. 

Currently the workflow builds the kernel modules on both `arm64` and `amd64`. After building the kernel modules, it installs the newly made kernel modules on both architectures as well. I think this is a better approach than #31 and #108 as we have access to both architectures to verify if there are compilation errors/runtime errors. 

CircleCI also offers GPU instances in which we could do testing on the newly build kernel modules. @aritger If you are interested in using CircleCI for this project let me know. I am happy to see if we can enable GPU instances on our OSS tier. More information on the CircleCI's OSS tier [here](https://circleci.com/open-source/).

With CircleCI, we also can publishes releases instead of just using tags for new releases of the driver. I think that would look a little cleaner for the community. 

This is the [link](https://app.circleci.com/pipelines/github/james-crowley/open-gpu-kernel-modules/7/workflows/14613590-26b5-4e28-b582-3de309cef378) to the current build.

Fixes #31 
Fixes #108

2022-05-12 17:42 UTC, TrojanerHD requested changes
See #48 or https://github.com/NVIDIA/open-gpu-kernel-modules/pull/31#discussion_r870948075

2022-05-12 17:42 UTC, TrojanerHD commented on .circleci/config.yml
> +        default: "-j`nproc`"
```suggestion
        default: "-j$(nproc)"
```

2022-05-12 17:42 UTC, TrojanerHD commented on .circleci/config.yml
> +        default: "-j`nproc`"
```suggestion
        default: "-j$(nproc)"
```

2022-05-12 17:42 UTC, TrojanerHD commented on .circleci/config.yml
> +          build-args: "-j`nproc`"
```suggestion
          build-args: "-j$(nproc)"
```

2022-05-12 17:42 UTC, TrojanerHD commented on .circleci/config.yml
> +          install-args: "-j`nproc`"
```suggestion
          install-args: "-j$(nproc)"
```

2022-05-12 18:52 UTC, james-crowley commented
@TrojanerHD Thanks for the catch! Just pushed the fix.

2022-05-13 18:21 UTC, PurHur commented
I highly recommend that it runs with github actions instead of circleci to be more open and remove complexity of the overall devops system. 
If its just needed for the testing pipeline this could be outsourced, but the base stuff need as simple as it could get.

2026-03-11 15:18 UTC, closed without merging