Fix device null pointer deref and add acpi bus query failure check
NVIDIA/open-gpu-kernel-modules pull request #216
Opened 2022-05-17 15:51 UTC by amada95

Makes use of `ACPI_FAILURE` macro to check successful operation of `acpi_bus_get_device`, and adds a null check before using the contents of `device`.

Fixes: #109 

_note: functional change, followup from PR #22_

2022-05-18 02:19 UTC, jarodsim commented
Yes, i think this fix work great

2022-05-18 07:32 UTC, mtijanic requested changes
Hi @amada95 , thank you for the contribution.

I see a couple of issues that need to be worked out still:
1. The newly added `status` variable is not declared anywhere. Please declare it at the top in line with the style of this file. Additionally, please at least ensure your changes compile successfully. 
2. The check is done in an `#if defined(NV_ACPI_BUS_GET_DEVICE_PRESENT)`. Should this be undefined, the check will be skipped and a null deref remains at `device->driver_data = NULL;`
3. In case of function call failure, we return early, but I believe we would still want to set `nvif_parent_gpu_handle` to NULL.

2022-05-18 18:36 UTC, amada95 commented
The requested changes have been implemented, let me know if there are any issues.

2022-05-19 18:33 UTC, mtijanic commented
Thank you, Amada, this looks good now. I'll start the internal test pipeline and get back to you on Monday.

2022-05-19 20:00 UTC, master7720 commented
i use arch btw.

2022-05-19 21:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NVIDIA/open-gpu-kernel-modules?pullRequest=216) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/NVIDIA/open-gpu-kernel-modules?pullRequest=216) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: amada95<br/>:x: niv<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NVIDIA/open-gpu-kernel-modules?pullRequest=216) it.</sub>

2022-05-26 06:46 UTC, amada95 commented
Hello! Just popping in, any updates on this PR?

2022-05-27 10:54 UTC, mtijanic commented
Hi Amada, sorry for the late response, I was out of office for a few days.

The status is this: This code has been removed from our primary development branch. It is still around in some of the release branches, where I expect we will merge it. However, for the very next release(s?), QA has already advanced too far and the branch is currently frozen. This means that if I merge the PR here, it would be clobbered by releases that are already in the pipeline.

So, I'll leave it open for the time being and merge when it gets merged internally.

Thanks for understanding.

2022-05-27 19:05 UTC, amada95 commented
Sounds good, thanks for the transparency and I wish you all the best of luck with that.

2022-06-04 21:27 UTC, amada95 commented
Accidentally renamed the main branch, reopening

2022-07-03 02:41 UTC, amada95 commented
Hello! Any updates? I just want to make sure this didn't get buried due to that accidental branch rename.

2022-07-04 10:58 UTC, mtijanic commented
Hey there, sorry for the late response.  From the previous comment:

> The status is this: This code has been removed from our primary development branch. It is still around in some of the release branches, where I expect we will merge it.

Looks like the function removal actually did make it into the next release QA pipeline, so the entire function is already gone from the repo (which is why github is telling you there are merge conflicts).

I don't think there's anything left to do here, so I'll close the PR. Please let me know if you disagree. And thanks again for the contribution, even if it didn't get merged!

2022-07-04 10:58 UTC, closed without merging